### ISSUE TITLE
Align the color swatches

### ISSUE THREAD

**Issue by GrantCuster** [components-ai/css.gui#118]
I imagine custom styling of inputs is a possible rabbithole, at the moment my top request is a way to align the color swatch inputs -- I think in my specific case right aligning them (with 'justify-content: space-between') would work, though I'm open to other ideas as well. If they had a consistent classname I could do it myself (though I can imagine you might want to approach it a different way).

![shotwin-2022-05-03_18-06-53](https://user-images.githubusercontent.com/679386/166574835-a7ea5178-1f54-45ae-b9ee-0ba4cd18ae1e.png)

**Comment by johno** [comment]
We got a quick win queued up to go in that makes the label sit on top of the input like the rest of our controls.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1424573/166586253-4d34be7a-6763-43af-8f10-c078b3585b97.png">

**Comment by GrantCuster** [comment]
heh, the best kind of solution. looks good!
