### ISSUE TITLE
Creating new background gradient does not work

### ISSUE THREAD

**Issue by GrantCuster** [components-ai/css.gui#126]
I've been told to keep the requests coming, so I am doing that :)

I tried out the BackgroundImage input. It doesn't seem to work for initializing a new gradient (maybe needs default stops to start?)

![gif-2022-05-04_10-39-05](https://user-images.githubusercontent.com/679386/166705846-093d5546-4848-4e84-8a32-d605c1caecb2.gif)

Additionally it seems like being able to remove a background image in the list would be helpful.

**Comment by GrantCuster** [comment]
Ah this was actually the result of a very hacky thing I did earlier to hide the breakpoint svgs (I hid all svgs which meant I couldn't see the stop buttons). I stopped doing that and we're all good.

**Comment by johno** [comment]
Ah good to know, and please do keep the reports/requests coming!
