### ISSUE TITLE
Option to hide breakpoint styles button (or hide it by default?)

### ISSUE THREAD

**Issue by GrantCuster** [components-ai/css.gui#145]
In our case I think it may cause confusion to users as to what it is for:

![shotwin-2022-05-05_09-17-21](https://user-images.githubusercontent.com/679386/166933267-f6dbb520-fbc0-4a3b-b3b8-fe875fcfcf30.png)

**Comment by johno** [comment]
Think we can definitely add an option to hide it.

**Comment by johno** [comment]
This is now released (`hideResponsiveControls` prop on `Editor`) in `@compai/css-gui@0.0.35`.

```js
import { useState } from 'react'
import { Editor, Inputs, styled } from '@compai/css-gui'
export function Demo() {
  const [styles, setStyles] = useState({})
  return (
    <>
      <Editor
        styles={styles}
        onChange={setStyles}
        hideResponsiveControls={true}
      >
        <Inputs.FontSize />
      </Editor>
      <styled.p styles={styles}>Hello, world!</styled.p>
    </>
  )
}
```

Docs: https://components.ai/open-source/css-gui/components/editor

**Comment by GrantCuster** [comment]
Perfect!
