### ISSUE TITLE
Variable fonts cause duplicate properties

### ISSUE THREAD

**Issue by deanblacc** [components-ai/css.gui#256]
Since we build up inputs based on whats in the styles object, if we add a variable font that manages `fontWeight` for example, then 2 controls are rendered

To reproduce:

https://user-images.githubusercontent.com/4340994/170103655-31acfd62-a56c-4ce4-acf6-27abd6346757.mov

**Comment by johno** [comment]
IIRC, a way to potentially remedy this is to use Google Font's stylesheet to specify the font weight right? So that way we don't need the top-level font weight property?

**Comment by deanblacc** [comment]
mmm im not sure that will fix it, unless im misunderstanging. I think the root problem is with how we manage children/controls. A variable font can add fontWeight to the styles object as a "dependant property" and when it does that the Editor sees the fontWeight property on the styles object and renders a new control for it. Thats what I've gathered so far anyway.

**Comment by johno** [comment]
Oh I follow now. Hmmm 🤔
