### ISSUE TITLE
Distinguish between responsive inputs and array inputs

### ISSUE THREAD

**Issue by tesseralis** [components-ai/css.gui#295]
currently, we store responsive values as arrays. however, we also store some types of inputs as arrays (like box shadow). We currently distinguish between them by having only a small set of inputs be responsive.

**Comment by johno** [comment]
Wonder if we want to do something similar to what I did for "multidimensional inputs" where I made a specific type to differentiate between its array value and a responsive array:

```ts
type MultidimensionalLength = {
  type: 'multidimensionalLength',
  value: Length[]
}
```
