### ISSUE TITLE
Color Picker: Theme Colors are going outside the container 

### ISSUE THREAD

**Issue by vaibhav111tandon** [components-ai/css.gui#370]
Color palettes are outside the main color-picker container.

Screenshot:
![screenshot-components ai-2022 06 13-13_05_44](https://user-images.githubusercontent.com/32813114/173303429-153478ec-013b-468c-af97-91bddcf8728d.png)

**Comment by mrmrs** [comment]
@vaibhav111tandon thanks for the catch!

**Comment by mrmrs** [comment]
Should be fixed now!
