### ISSUE TITLE
Bug: Input Fields with empty value become NaN on drag

### ISSUE THREAD

**Issue by tarngerine** [components-ai/css.gui#43]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/1629901/165183702-ded854d1-0b9b-470b-a188-a88ffd13f306.png">

go to shadows example
open text shadow
drag on first empty input

expected: empty = 0 and go from there

actual: nan error

**Comment by johno** [comment]
Thanks for reporting! This should now be fixed.
