### ISSUE TITLE
Small feature request: a way to turn style object into a CSS string

### ISSUE THREAD

**Issue by GrantCuster** [components-ai/css.gui#51]
Is there an easy way for me to convert the style object into a CSS string? I want to stick css.gui styles directly into a style element.

**Comment by johno** [comment]
Definitely something we want to support, goal is to have many different "outputs" which can even be different flavors of CSS. So we'll get to an initial base/vanilla CSS string output shortly!

Thinking something similar to:

```js
import { stringify } from '@compai/css-gui'

const someStyles = {/** ... */}
const someOptionalTheme = {/** ... */}
const css = stringify.css(someStyles, {
  selector: '.my-class',
  theme: someOptionalTheme
})
```

## Implementation details

(Mostly writing it here for when we get to it in the next couple days)

1. Call `toCSSObject` to get stringified values of all complex properties
2. Partition styles based on media queries (if responsive styles are present)
3. Create a class name (likely a hash if one isn't given)
4. Stringify objects for each media query and add to declarations wrapped with selector
5. Wrap in media queries (if present)

**Comment by GrantCuster** [comment]
Sounds great!

**Comment by GrantCuster** [comment]
Awesome! Will try it tomorrow.

**Comment by GrantCuster** [comment]
Working great for me so far
