### ISSUE TITLE
borderStyle is not recognized

### ISSUE THREAD

**Issue by GrantCuster** [components-ai/css.gui#57]
Maybe it's already on your list, but I get:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'type')

Call Stack
getInputComponent
node_modules/@compai/css-gui/dist/index.js (6172:0)
```

when trying to use borderStyle. borderWidth and borderColor work fine.

**Comment by johno** [comment]
Thanks for reporting, this should now be fixed in `@compai/css-gui@0.0.7`.
