### ISSUE TITLE
Certain export formats missing CSS properties

### ISSUE THREAD

**Issue by colepeters** [components-ai/css.gui#616]
I'm noticing that some export formats appear to be missing several CSS properties that I've specified on my component.

Here's the correct output from the HTML + CSS exporter:

```html
<style>
  .css-gui-f5333c {
    background-color: #e7284e;
    padding-bottom: 8px;
    padding-right: 16px;
    border-radius: 4px;
    padding-left: 16px;
    -webkit-transition: background-color 125ms 0ms cubic-bezier(0, 0, 1, 1);
    transition: background-color 125ms 0ms cubic-bezier(0, 0, 1, 1);
    padding-top: 8px;
    cursor: pointer;
    border: 0px none transparent;
    color: #ffffff;
  }

  .css-gui-f5333c:hover {
    background-color: #ac0e2e;
  }
</style>

<button class="css-gui-f5333c">Hello, World!</button>
```

However:

<details>
  <summary>Incorrect output from Theme UI exporter</summary>

```js
/** @jsxImportSource theme-ui */
export default function Component() {
  return (
    <button
      sx={{
        color: 'gray.11',
        ':hover': { backgroundColor: 'red.4' },
        border: '0px none transparent',
        cursor: 'pointer',
        transition: 'background-color 125ms 0ms cubic-bezier(0, 0, 1, 1)',
        backgroundColor: 'red.6',
      }}
    >
      Hello, World!
    </button>
  )
}
```
</details>

<details>
  <summary>Incorrect output from the Enhance SFC export</summary>

```js
export default function Component({ html, state = {} }) {
  return html`
    <button
      style={{
        "color":"gray.11",
        ":hover":{"backgroundColor":"red.4"},
        "border":"0px none transparent",
        "cursor":"pointer",
        "transition":"background-color 125ms 0ms cubic-bezier(0, 0, 1, 1)",
        "backgroundColor":"red.6"
      }}
    >
      Hello, World!
    </button>
    `
}
```
</details>

_(As an aside, I'm pretty sure the Enhance exporter may still be in progress, so possibly ignore this but: styles for Enhance SFCs should be an embedded `<style>` block rather than an object on the `style` attribute.)_

Based on my component definition, the above exports are missing:

- `paddingTop`
- `paddingBottom`
- `paddingLeft`
- `paddingRight`
- `borderRadius`

At first I thought perhaps the exporters relying on JS may all be bugging, but the Emotion exporter renders the expected output:

<details>
  <summary>Correct output from the Emotion exporter</summary>

```js
/** @jsxImportSource @emotion/react */
export default function Component() {
  return (
    <button
      css={{
        color: "#ffffff",
        ":hover": { backgroundColor: "#ac0e2e" },
        border: "0px none transparent",
        cursor: "pointer",
        paddingTop: "8px",
        transition: "background-color 125ms 0ms cubic-bezier(0, 0, 1, 1)",
        paddingLeft: "16px",
        borderRadius: "4px",
        paddingRight: "16px",
        paddingBottom: "8px",
        backgroundColor: "#e7284e",
      }}
    >
      Hello, World!
    </button>
  );
}
```
</details>

Not sure if this is helpful, but [here's a link to my published component](https://components.ai/u/colepeters/files/pub/cl87mkwis000409l28od3jp3e).

Happy to provide any other details as needed!

**Comment by mrmrs** [comment]
@colepeters thanks for catching all of this. I *believe* we've got these issues buttoned up now but let me know if you run into anything else.

**Comment by colepeters** [comment]
@mrmrs Just took a look, and it looks good to me! Many thanks :)

**Comment by kristoferjoseph** [comment]
This is aces!
Y'all are amazing
