### ISSUE TITLE
Easy way to set color palette

### ISSUE THREAD

**Issue by GrantCuster** [components-ai/css.gui#94]
I'd like an easy way to set some preset colors for the color picker input. This may be possible through the `theme` option but I didn't get it to work on my naive try of feeding `{ colors: { red: "red", blue: "blue" } }` into the theme prop of the editor.

**Comment by mrmrs** [comment]
@GrantCuster on it! Should have something soon.

**Comment by johno** [comment]
In the near future we'll be working on making this more streamlined, but I'll link the latest docs as soon as they finish building.

**Comment by johno** [comment]
Should now be published as `@compai/css-gui@0.0.22`. The docs: https://components.ai/open-source/css-gui/imports/color

**Comment by GrantCuster** [comment]
Cool, yea this is working great for the color palette -- and I think I'm now understanding more how a theme could be utilized in general -- lots of interesting possiblities!

**Comment by mrmrs** [comment]
@GrantCuster part of the thinking is we want a user / team to be able to define any set of constraints for any css property input and that data can live in a theme. This was part of the original thinking around design tokens and what you could do with them. Can take something like css stats, scrape a site for it's CSS, reduce it to discrete values, than use that to collapse generative space for styling a set of headless ui components. We're really excited about the possibilities there.

**Comment by GrantCuster** [comment]
> Can take something like css stats, scrape a site for it's CSS, reduce it to discrete values, than use that to collapse generative space for styling a set of headless ui components.

Ah yea that is a cool idea!

For Sprout I think we'll start with pretty freeform individual block styling (already in progress). Ultimately I'm thinking we'd like to rebuild the current styling entirely as a theme you could swap out -- so you'd have base theme level and then you could further tweak on top of that... that seems really cool! But taking it one step at a time for now.
